# Problem 1

In [9]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris= np.random.randint(0,11,size=(5,))

# 3 - matris'in boyutunu öğrenin
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
yeniBoyut= matris.reshape((1,5))
# 5 - matris'in boyut sayısını öğrenin
print(yeniBoyut)

(5,)
[[9 2 6 6 5]]


# Problem 2

In [29]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np 
matris= np.arange(1,11,2).reshape((5,1))
print(matris)
# 2 - Oluşturduğunuz matrisi parçalayın
parcalanmıs = np.split(matris,5)
for parcala in parcalanmıs:
    print(parcala)

# 3 - Parçalanmış matrisleri birleştirin
parcalanmıs=np.concatenate(parcalanmıs,axis=0)
print(parcalanmıs)


[[1]
 [3]
 [5]
 [7]
 [9]]
[[1]]
[[3]]
[[5]]
[[7]]
[[9]]
[[1]
 [3]
 [5]
 [7]
 [9]]


# Problem 3

In [37]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np 
sayilar= np.random.choice(np.arange(1,101,2), size=10, replace= False).reshape((5,2))
print(sayilar)

# 2 - matris'in özelliklerini inceleyin

sayilar = np.array(print(sayilar))
print("Boyut:", matris.shape)
print("Eleman sayısı:", matris.size)
print("Veri tipi:", matris.dtype)
print("Minimum değer:", matris.min())
print("Maksimum değer:", matris.max())
print("Toplam:", matris.sum())
print("Ortalama:", matris.mean())




[[95 93]
 [17 97]
 [99 47]
 [87 85]
 [23 37]]
[[95 93]
 [17 97]
 [99 47]
 [87 85]
 [23 37]]
Boyut: (5, 1)
Eleman sayısı: 5
Veri tipi: int32
Minimum değer: 1
Maksimum değer: 9
Toplam: 25
Ortalama: 5.0
